DROP TABLE IF EXISTS TB_HEROIS;
CREATE TABLE TB_HEROIS(
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    NOME TEXT NOT NULL,
    PODER TEXT NOT NULL,
)
--Create
INSERT INTO TB_HEROIS(NOME,PODER)
VALUES
    ('FLASH','VELOCIDADE'),
    ('AQUAMAN','FALAR COM ANIMAIS'),
    ('BATMAN','DINHERIO')
--read
SELECT * FROM TB_HEROIS WHERE NOME = 'FLASH'

--update
UPDATE TB_HEROIS
SET NOME = 'GOKU',PODER= 'DEUS'
WHERE ID = 1

--delete
delete from TB_HEROIS WHERE ID =2 